apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: dfr1d9ottv8xsc
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 5s
